/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("application")
}

dependencies {
    implementation(project(":logic"))
}

application {
    // Define the main class for the application.
    mainClass = "de.hexgame.algorithm.Main"
}
